qcacld-3.0: Add missing include
Fix build error if defined WLAN_ICMP_DISABLE_PS

/drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_tx_rx.c: In function ‘wlan_hdd_latency_opt’:
/drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_tx_rx.c:415:3: error: implicit declaration of function ‘sme_ps_enable_auto_ps_timer’ [-Werror=implicit-function-declaration]
   sme_ps_enable_auto_ps_timer(WLAN_HDD_GET_HAL_CTX(adapter),
   ^